on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: true
    - name: Setup vcpkg
      uses: lukka/run-vcpkg@v11
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1

    - name: Build
      run: msbuild ./Bouny/Bouny.vcxproj /p:Configuration=Release /p:Platform=x64
    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        name: Bouny
        path: |
          ./Bouny/x64/Release/*.dll
          ./Bouny/x64/Release/*.pdb
